Repository Catfriend1/syncthing-android, pull requests merged in 2021-09, with the labels that each got.

#837 Schedule a backup stop job when running on schedule (fixes #803)
  app/src/main/java/com/nutomic/syncthingandroid/service/RunConditionMonitor.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncTriggerJobService.java
  app/src/main/java/com/nutomic/syncthingandroid/util/JobUtils.java
Labels: bug

#845 Make Syncthing Camera a QuickSetting tile (fixes #844)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/QuickSettingsTileCamera.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
  app/src/main/res/drawable/ic_qs_camera.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_settings.xml
Labels: enhancement

#846 UI for untrusted devices, encrypted folder sharing (fixes #724)
  app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java
  app/src/main/res/layout/item_device_form.xml
  app/src/main/res/layout/item_folder_form.xml
Labels: enhancement, upstream
