Repository Catfriend1/syncthing-android, pull requests merged in 2024-12, with the labels that each got.

#1168 Allow configuring time schedule interval
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RunConditionMonitor.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_settings.xml
Labels: enhancement

#1195 Allow empty device name (fixes #1185)
  app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java
Labels: bug

#1196 WebUI password not migrated after switching from official app to forked app (fixes #1189)
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: bug

#1198 Docker, Dependabot and GitHub Workflows
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/build-app.yaml
  .github/workflows/build-builder.yaml
  .github/workflows/image-builder-template.yaml
  .github/workflows/release-app.yaml
  docker/Dockerfile
  docker/README.md
  docker/prebuild.sh
Labels: build

#1210 Add exit action to notification (fixes #1121)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/NotificationHandler.java
Labels: enhancement
