Repository Catfriend1/syncthing-android, pull requests merged in 2025-05, with the labels that each got.

#1371 Add action "Release app"
  .github/workflows/actions-setup.txt
  app/build.gradle.kts
Labels: build

#1376 importConfig: Ignore outdated user pref (fixes #1375)
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: bug

#1378 Update README.md
  README.md
Labels: Documentation

#1379 Update README.md
  README.md
Labels: Documentation

#1384 Support floats for fsWatcherDelayS option (fixes #1365)
  app/src/main/java/com/nutomic/syncthingandroid/model/Folder.java
  app/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java
Labels: bug

#1386 Syncthing Web UI: default HOME env folder = /storage/emulated/0/syncthing (fixes #764)
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
Labels: enhancement

#1388 Fix sdcard root path not offered in gear icon folder picker (fixes #1309)
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/util/FileUtils.java
Labels: bug

#1389 Add forum and privacy policy links to Settings/About
  app/res.lnk
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_settings.xml
Labels: enhancement

#1390 Make release builds reproducible #698 (fixes #1383)
  syncthing/build-syncthing.py
  syncthing/build.gradle
Labels: build

#1391 Clarify strings: bind_active_network option, fix lint values-iw (fixes #1306)
  app/lint.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/locales_config.xml
  app/strings.xml.lnk
Labels: enhancement

#1394 Revert bind_active_network due to bug
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_settings.xml
  scripts/res-string-remover.ps1
Labels: bug

#1397 Create ".nomedia" in ".stversions" subfolder if a new folder is added (fixes #1396)
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java
Labels: enhancement

#1402 Update dependencies, enable kotlin compiler, migrate to TOML versions config
  .dockerignore
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: build, dependencies

#1401 Switch from oss-licenses-plugin to AboutLicenses plugin (fixes #1400)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/activities/LicenseActivity.kt
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#1403 Remove play publisher plugin and script
  app/build.gradle.kts
  prepare-release.bash
  scripts/App_build_and_release.cmd
  scripts/SyncthingNative_update_and_build.cmd
  scripts/install_minimum_android_sdk_prerequisites.py
  scripts/postbuild_copy_apk.cmd
Labels: publishing

#1404 remove cfgOption insecureAllowOldTLSVersions
  app/src/main/java/com/nutomic/syncthingandroid/model/Options.java
  app/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java
Labels: upstream

#1410 Send an intent when a shared folder finished syncing (fixes #1409)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  wiki/Integrate-your-app-with-Syncthing-receive-folder-sync-status.md
Labels: enhancement

#1412 Expert option: Run custom shell script after folder sync completed
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  app/src/main/java/com/nutomic/syncthingandroid/util/Util.java
  app/src/main/res/drawable/terminal_24dp.xml
  app/src/main/res/layout/activity_folder.xml
  app/src/main/res/values/strings.xml
  scripts/debug/android/testFolder/.stfolder/demo1.sh
  scripts/debug/android/testFolder/.stfolder/demo2.sh
Labels: enhancement

#1415 Cats love pizza
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_settings.xml
Labels: enhancement

#1416 Show sync conflicts on the folder tab (fixes #1130)
  app/src/main/java/com/nutomic/syncthingandroid/model/CachedFolderStatus.java
  app/src/main/java/com/nutomic/syncthingandroid/model/LocalCompletion.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  app/src/main/java/com/nutomic/syncthingandroid/util/Util.java
  app/src/main/java/com/nutomic/syncthingandroid/views/FoldersAdapter.java
  app/src/main/res/layout/item_folder_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1417 Persist backup folder on restore, restoring from backup is not wise (fixes #1375)
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: bug

#1419 APK version v1.29.6.3, cleanup unused weblate translation strings
  app/src/main/play/release-notes/en-US/default.txt
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-ca-rES/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  build.gradle.kts
  wiki/Remote-Control-by-Broadcast-Intents.md
Labels: build

#1425 Fix libSyncthingNative.so packaging for armeabi-v7a (fixes #1421)
  syncthing/build-syncthing.py
Labels: build

#1441 Update release key which was over 5 years old (fixes #1440)
  app/src/main/play/release-notes/en-US/default.txt
  build.gradle.kts
  wiki/Switch-between-releases_Verify-APK-is-genuine.md
Labels: build

#1443 Fix conflicts between debug and release APK (fixes #1442)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/model/Options.java
  app/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java
  app/src/main/play/release-notes/en-US/default.txt
Labels: build

#1444 Wiki and Readme update
  README.md
  wiki/Build-instructions.md
  wiki/Building-and-Development.md
Labels: Documentation

#1445 Issue template update
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  scripts/debug/adb_get_log.cmd
  scripts/debug/adb_push_config_xml.cmd
Labels: Documentation

#1456 RestApi: fix hang by reducing subsequent conflict detection calls
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
Labels: bug

#1455 Fix web UI user name null pointer exception (fixes #1450)
  app/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java
  scripts/debug/adb_forward_webui.cmd
Labels: bug
